### ISSUE TITLE
[PE-D][Tester B] Regex for inputs of some prefixes not provided in the UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T15-3/tp#101]
Currently, there is no explicit mention of the accepted regex for `name`, `email`, `address`, `phone`, and `instrument` fields in the UG. This can be problematic for new users of the app because the definition of a "valid" input is unclear. For example in the add command, the UG does not state how to properly format the names, phone numbers, emails etc. and what special characters can be included in each of the inputs. 

![image.png](https://raw.githubusercontent.com/jayllo-c/ped/main/files/d4a6918c-2ff0-410a-950b-d44ec6ab011d.png)

The regex should be explicitly stated in the UG to help users understand the limitations of the app earlier on instead of relying on the failure messages generated by the app.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: jayllo-c/ped#15

**Comment by casaarlai** [comment]
This was completed by @triciiaaa
