### ISSUE TITLE
[PE-D][Tester B] Assign command lacks comprehensive error message for invalid indexes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T15-3/tp#81]
![image.png](https://raw.githubusercontent.com/jayllo-c/ped/main/files/0a191b7b-8fcc-42cf-9792-f31dd82b0e4c.png)

The expected behaviour of the application is to tell the user when the user inputs something invalid. In this case, it did, but the application did not properly specify which of the indexes is incorrect, which will hinder how convenient it is to find which of the indexes causes an issue.

This error message can be replicated as long as you input one or more invalid indexes in the assign command.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jayllo-c/ped#6

**Comment by brennalaurentan** [comment]
Unable to do anything about this as the current behaviour is not strictly 'incorrect' but 'can be better' and hence would be classified as a feature change which is not allowed in v1.4
