### ISSUE TITLE
[PE-D][Tester B] Cannot assign multiple instruments to people

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T15-3/tp#87]
The application claims to be able to assign instruments to band members. However, one important consideration missed and not implemented is the fact that people within the band may be proficient in multiple different instrument and hence can be assigned to more than one instrument. However, the current code behaviour does not allow the adding of multiple instruments. 

If we use the `assign` command, if the user has an instrument already assigned then the current instrument will be replaced with the new one provided as an argument in the `assign` command, else it will just assign one instrument.

The screenshots below highlight this problem. 

![image.png](https://raw.githubusercontent.com/jayllo-c/ped/main/files/28576eb6-3587-4abb-833a-dc76a2fc610d.png)

![image.png](https://raw.githubusercontent.com/jayllo-c/ped/main/files/d3d094a3-5a26-4100-b4ce-f0befe08d4fa.png)

Furthermore, we cannot create another entry with the same person because duplicate persons are not allowed as shown in the following screenshot: 

![image.png](https://raw.githubusercontent.com/jayllo-c/ped/main/files/8376b947-e871-4d1d-aedb-9fa92bbc3ac4.png)

In any case, we can only assign one instrument to each band member, limiting the functionality of the app.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jayllo-c/ped#7

**Comment by triciiaaa** [comment]
Closed as the current implementation only allows one instrument to be assigned to each member. Changing this implementation would be considered a feature change.
