### ISSUE TITLE
[PE-D][Tester C] Parameter tags are not case-insensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T15-3/tp#88]
This is a minor issue, but if you are considering to improve the usability, the parameter tags can be made case-insensitive :)

![image.png](https://raw.githubusercontent.com/larainezo/ped/main/files/822632f6-656b-4f93-8d59-a8e496781089.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: larainezo/ped#13

**Comment by casaarlai** [comment]
Closed as this is a suggestion rather than an actual bug

**Comment by casaarlai** [comment]
Closed as this is a suggestion rather than an actual bug
