### ISSUE TITLE
[PE-D][Tester A] Mismatch of command structure and example

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T15-3/tp#91]
![image.png](https://raw.githubusercontent.com/faaheem13/ped/main/files/79998d62-f543-4684-bb55-c004a022fa69.png)

This image mentions using the "att" command to unmark a specific index's attendance, however, according to the rest of the UG and their app, att is to mark instead. 

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: faaheem13/ped#8

**Comment by brennalaurentan** [comment]
Issue has now been fixed in an earlier pull request.
