### ISSUE TITLE
[PE-D][Tester A] Minor Documentation Error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T15-3/tp#92]
![image.png](https://raw.githubusercontent.com/faaheem13/ped/main/files/9f637e77-d845-471d-94e1-0e29ad2722fa.png)

Similar to another issue pointed out, the example does not include the correct format of command as in the rest of the UG which may lead to misunderstanding. Again, I believe this to be very minor and easily fixable.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: faaheem13/ped#9

**Comment by triciiaaa** [comment]
This was completed by @casaarlai.
