### ISSUE TITLE
[PE-D][Tester B] Birthday field accepts unrealistic birthdays 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T15-3/tp#96]
Currently, we can add or edit contacts with the birthday prefix as long as it is in the provided format YYYY-MM-DD and the birthday is between the day 0001-01-01 and today as shown in the screenshot below. 

![image.png](https://raw.githubusercontent.com/jayllo-c/ped/main/files/6bf847af-f9c9-4156-8929-1ab0548009f0.png)

However, this is not realistic since we will not be adding people born a substantially long time ago or newborn infants into the band address book. As such, the **range of birthdays accepted should be limited** to better fit the ages of people that the app intends to store.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jayllo-c/ped#10

**Comment by brennalaurentan** [comment]
Unable to do anything about this code-wise as it would be classified as a functionality change, but will add to the 'Known Issues' section of the User Guide

**Comment by brennalaurentan** [comment]
Will not be fixing as it is entirely up to the discretion of the user, to choose the contacts they would like to add into BandBook. Adding data validation for this field and limiting the birth date of contacts that can be added would be reducing the functionality and the freedom of users, which is not our intention. Birth dates such as 0001-01-01, while dated and unlikely, are in fact not invalid.
